export const mockData = [
    {
      id: 1,
      name: "Bafl Investments",
      email: "Bafl@investments.com",
      phoneNumber: "0311-0078601",
      city: "Karachi",
      industry: "Bank",
      assignedLimit: "10000",
      remainingLimit: "10000",
    },
    {
      id: 2,
      name: "Atlas Bank",
      email: "contact@atlasbank.com",
      phoneNumber: "0322-9876543",
      city: "Lahore",
      industry: "Bank",
      assignedLimit: "15000",
      remainingLimit: "12000",
    },
    {
      id: 3,
      name: "Faysal Holdings",
      email: "info@faysalholdings.com",
      phoneNumber: "0300-1234567",
      city: "Islamabad",
      industry: "Investment",
      assignedLimit: "20000",
      remainingLimit: "18000",
    },
    {
      id: 4,
      name: "Meezan Financials",
      email: "meezan@financials.com",
      phoneNumber: "0312-3456789",
      city: "Karachi",
      industry: "Bank",
      assignedLimit: "12000",
      remainingLimit: "10000",
    },
    {
      id: 5,
      name: "HBL Capital",
      email: "hbl@capital.com",
      phoneNumber: "0345-6789012",
      city: "Lahore",
      industry: "Investment",
      assignedLimit: "18000",
      remainingLimit: "16000",
    },
    {
      id: 6,
      name: "UBL Ventures",
      email: "contact@ublventures.com",
      phoneNumber: "0311-8765432",
      city: "Karachi",
      industry: "Bank",
      assignedLimit: "25000",
      remainingLimit: "23000",
    },
    {
      id: 7,
      name: "Alfalah Securities",
      email: "support@alfalahsecurities.com",
      phoneNumber: "0301-3456789",
      city: "Islamabad",
      industry: "Investment",
      assignedLimit: "22000",
      remainingLimit: "20000",
    },
    {
      id: 8,
      name: "MCB Investments",
      email: "info@mcbinvestments.com",
      phoneNumber: "0332-4567890",
      city: "Karachi",
      industry: "Investment",
      assignedLimit: "14000",
      remainingLimit: "13000",
    },
    {
      id: 9,
      name: "Soneri Bank",
      email: "soneri@bank.com",
      phoneNumber: "0321-9876543",
      city: "Lahore",
      industry: "Bank",
      assignedLimit: "11000",
      remainingLimit: "9000",
    },
    {
      id: 10,
      name: "Bank Islami",
      email: "contact@bankislami.com",
      phoneNumber: "0312-7890123",
      city: "Karachi",
      industry: "Bank",
      assignedLimit: "17000",
      remainingLimit: "15000",
    },
    {
      id: 11,
      name: "JS Global Capital",
      email: "jsglobal@capital.com",
      phoneNumber: "0309-1234567",
      city: "Islamabad",
      industry: "Investment",
      assignedLimit: "21000",
      remainingLimit: "19000",
    },
    {
      id: 12,
      name: "Silk Bank",
      email: "support@silkbank.com",
      phoneNumber: "0321-6549871",
      city: "Lahore",
      industry: "Bank",
      assignedLimit: "16000",
      remainingLimit: "14000",
    },
    {
      id: 13,
      name: "Askari Securities",
      email: "askari@securities.com",
      phoneNumber: "0302-8765432",
      city: "Rawalpindi",
      industry: "Investment",
      assignedLimit: "18000",
      remainingLimit: "17000",
    },
    {
      id: 14,
      name: "Standard Chartered",
      email: "standard@chartered.com",
      phoneNumber: "0301-2345678",
      city: "Karachi",
      industry: "Bank",
      assignedLimit: "25000",
      remainingLimit: "22000",
    }]