 export const orgData = [
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
        {
          organizationName: "Bafl Investments",
          email: "Bafl@investments.com",
          phoneNumber: "0311-0078601",
          city: "Karachi",
          industry: "Bank",
          assignedLimit: "10000",
        },
      ]